server:
  port: 8080

# 应用配置
app:
  config:
    # 版本,方便通过接口版本升级
    api-version: v1
    # 跨域,开发阶段可以设置为 * 不限制
    cross-origin: "*"

# ChatGLM SDK Config
chatglm:
  sdk:
    config:
      api-host: https://open.bigmodel.cn/
      api-secret-key: 6fbc6c46a84a201fad03b6de40253619.2WNgqPQhA34dEEoq

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
